### ISSUE TITLE
Suggestion: "Format as single line" to convert multi-line statement back to a single line

### ISSUE THREAD

**Issue by richellis** [aryamansharda/EditKitPro#1]
I'd like the inverse of the "Format as multi-line" command. See also: https://github.com/aheze/Multiliner/issues/8

Use case: I've split an `init` or function declaration into multiple lines because it exceeds my team's preferred line length. But now I've removed a parameter or two and so I'd like to quickly be able to switch it back to a more-compact single line statement.

**Comment by aryamansharda** [comment]
Sounds great - thanks for the suggestion! I can get a basic version out today that will reformat the existing line into a single one and then can spend some time this weekend playing around with how to do that reliably across the entire file 👍

**Comment by aryamansharda** [comment]
Implemented and submitted to App Store! This will be available in v1.4 🚀

**Comment by richellis** [comment]
Wow, thanks! 🚀
